spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/crewledger
spring.datasource.username=crewledger
spring.datasource.password=crewledger

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Docker Compose
spring.docker.compose.lifecycle-management=start-and-stop